MESSAGE
    "DELETAR REGISTRO?"
    VIEW-AS ALERT-BOX QUESTION BUTTONS YES-NO-CANCEL
    TITLE "ATTENTION" UPDATE lChoice AS LOGICAL.
    
//ALTERNATIVAS PARA CADA BOTÃO
    IF lChoice = YES THEN
    DO:
//APAGAR REGISTRO    
        MESSAGE "REGISTRO APAGADO."
        VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
    END.    ELSE DO:
//CANCELAR MENSAGEM    
    IF lChoice = ? THEN
    DO:
        MESSAGE "MENSAGEM CANCELADA!"
        VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
    END.    ELSE DO:
//NÃO APAGAR REGISTRO           
        MESSAGE "REGISTRO NÃO APAGADO!"
        VIEW-AS ALERT-BOX INFORMATION BUTTONS OK.
    END.
END.

